config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month' 
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :require_permission, only: [:index, :show]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  
  def index
    if params[:search].present?
      @users = User.where("name LIKE ?", "%#{params[:search]}%").paginate(page: params[:page])
      @title = "検索結果"
    else
      @users = User.paginate(page: params[:page])
      @title = "ユーザ一覧"
    end
  end
      
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "新規作成に成功しました。"
      redirect_to user_path(@user)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to user_path(@user)
    else
      render :edit
    end 
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
   def edit_basic_info
   end
  
   def update_basic_info
     if @user.update_attributes(basic_info_params)
       flash[:success] = "#{@user.name}の基本情報を更新しました。"
     else
       flash[:danger] = "#{@user.name}の更新は失敗しました。
       <br>" + @user.errors.full_messages.join("<br>")
     end
     redirect_to user_path
   end

  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
  end
  
  def basic_info_params
    params.require(:user).permit(:department, :basic_time, :work_time)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
   <%= render 'shared/error_messages', object: @user %>
   
   <%= f.label :name, class: "label-#{yield(:class_text)}" %>
   <%= f.text_field :name, class: "form-control" %>
      
   <%= f.label :email, class: "label-#{yield(:class_text)}" %>
   <%= f.text_field :email, class: "form-control" %>
      
   <%= f.label :department, class: "label-#{yield(:class_text)}" %> 
   <%= f.text_field :department, class: "form-control" %>
      
   <%= f.label :password, class: "label-#{yield(:class_text)}" %>
   <%= f.password_field :password, class: "form-control" %>
      
   <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
   <%= f.password_field :password_confirmation, class: "form-control" %>
      
   <%= f.submit yield(:button_text), 
    class: "btn btn-primary btn-block btn-#{yield(:class_text)}, form_btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h1>アカウント情報の更新</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "edit_basic_info") %>
<% provide(:button_text, '更新') %>

<div class="row">
  <div class="col-md-7 col-md-offset-2">
    <h1>基本情報の更新</h1>
    <%= form_with(model: @user, url: update_basic_info_user_path, local: true, method: :patch) do |f| %>

       <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
       <%= f.time_field :work_time, class: "form-control" %>
       
       <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
       <%= f.time_field :basic_time, class: "form-control" %>
       
       <%= f.submit yield(:button_text),
         class: "btn btn-primary btn-block btn-#{ yield(:class_text)}, form_btn" %>
       
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
　

  <div class="col-md-10 col-md-offset-1">
    <h1><%= @title %></h1>
    
    <%= form_tag(users_path, method: :get, class: "form-inline text-right") do %>
      <div>
        <%= label_tag :search, "ユーザー名検索", class: "search-form-name" %>
      </div>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "キーワードを入力" %>
        <span class="input-group-btn">
          <%= submit_tag "検索", class: "btn btn-primary btn-search" %>
        </span>
      </div>
    <% end %>
      
    <%= will_paginate %>
    <table class="table table-condensed table-hover", id= "table-users">
      <thead>
        <tr>
          <th><%= User.human_attribute_name :name %></th>
        </tr>
      </thead>
      
      <% if @users.any? %>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user, class: "user-list" %></td>
          <td></td>
          <td></td>
          <td>
            <% if current_user.admin? && !current_user?(user) %>
              <%= link_to "基本情報編集", edit_basic_info_user_path(user), class: "btn btn-success table-btn" %>
              <%= link_to "削除", user_path(user), method: :delete,
                  data: { confirm: "#{user.name} を削除してよろしいですか？" }, class: "btn btn-danger table-btn" %>
　　　　　　<% end %>
          </td>
        </tr>
      <% end %>
      <% else %>
        <tr>
          <td colspan="4">該当するユーザーは見つかりませんでした。</td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate %>
  </div>

app/views/users/new.html.erb
<% provide(:title, "new") %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h1>アカウント作成</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-condensed text-center">
    <tr>
      <td class="col-lg-5">
        <div class="btn-users-show">
          <%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-sm" %>
          時間管理表
          <%= link_to " ⇨", user_path(date: @first_day.next_month), class: "btn btn-primary btn-sm" %>

        </div>
      </td>
      <td class="col-sm-3">指定勤続時間 : <%= format_basic_info(@user.work_time) %></td>
      <td class="col-sm-3">基本時間 : <%= format_basic_info(@user.basic_time) %></td>
      <td class="col-1">初日 : <%= l(@first_day, format: :short) %></td>
    </tr>
  </table>
  <table class="table table-bordered table-condensed table-user text-center">
    <tr>
      <td class="col-lg-5">所属 : <%= @user.department.present? ? @user.department : "未所属" %></td>
      <td class="col-md-3">氏名 : <%= @user.name %></td>
      <td class="col-1">コード</td>
      <td></td>
      <td class="col-sm-2">出勤日数 : <%= @worked_sum %> 日 </td>
      <td class="col-sm-1">締め : <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div>
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <table class="table table-bordered table-striped table-condensed table-list">
    <thead>
      <tr>
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="8">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th colspan="6" class="table-cell"></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>  
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= day.worked_on.sunday? ? 'sunday' : (day.worked_on.saturday? ? 'saturday' : '') %>">
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td>
            <%= l(day.started_at&.change(min: (day.started_at.min / 15) * 15), format: :time_hour) if day.started_at.present? %>
          </td>
          <td>
            <%= l(day.started_at&.change(min: (day.started_at.min / 15) * 15), format: :time_minutes) if day.started_at.present? %>
          </td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance btn-block" %>
            <% end %>
          </td>
          <td colspan="6">
            <%= l(day.finished_at&.change(min: (day.finished_at.min / 15) * 15), format: :time_hour) if day.finished_at.present? %>
          </td>
          <td>
            <%= l(day.finished_at&.change(min: (day.finished_at.min / 15) * 15), format: :time_minutes) if day.finished_at.present? %>
          </td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at&.change(min: (day.started_at&.min / 15) * 15), 
                                            day.finished_at&.change(min: (day.finished_at&.min / 15) * 15)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
       <tr>
        <td colspan="2">累計日数</td>
        <td colspan="11">総合勤務時間</td>
        <td>累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
          <% total_work_time = format_basic_info(@user.work_time).to_f * @worked_sum %>
          <% total_work_time = 0 if @worked_sum == 0 %>
        <td colspan="11"><%= total_work_time %></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>
  </table>
</div>